config/routes.rb
Chapter09::Application.routes.draw do
  root :to => 'home#index'
  match "profile" => "users#profile"
  match "dashboard" => "users#dashboard"
  match "/signup" => "users#new"
  match "signin" => "sessions#new", via: :get
  match "login" => "sessions#new", via: :get
  match "login" => "sessions#create", via: :post
  match '/signout', to: 'sessions#destroy', via: :delete 
  match '/users' => 'users#create', :via => :post
  match '/order' => 'users#order', :via => :post

  match ':controller(/:action(/:id))(.:format)'
end

app/models/billing_information.rb
class BillingInformation < ActiveRecord::Base
  attr_accessible :address, :card_number, :city, :country, :expiration_date, :name, :payment_method, :postal_code, :same_as_shipping_information, :state, :user_id

  belongs_to :user
end

app/models/shipping_information.rb
class ShippingInformation < ActiveRecord::Base
  attr_accessible :address, :city, :country, :name, :postal_code, :state, :user_id
  
  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :birthday, :comments, :email, :heliskiing, :name, :password_hash, :pickle, :planet, :walnut, :spam, :password, :password_confirmation
  validates :password, confirmation: true
  validates :email, :presence =>true

  include BCrypt

  has_one :billing_information
  has_one :shipping_information

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def authenticate(params_password)
    password == params_password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_to dashboard_url
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out 
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,  only: [:profile, :dashboard, :order]

  def new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user 
      flash[:success] = "Welcome !"  
      redirect_to dashboard_url
    else
      flash[:error] = "Invalid email/password combination"
      render :new
    end
  end

  def profile
    @billing_information = current_user.billing_information || BillingInformation.new
    @shipping_information = current_user.shipping_information || ShippingInformation.new
  end

  def dashboard
    render :process
  end

  def test
    render :text => "session user id: #{session[:user_id]}"
  end

  def order
    begin 
      @billing_information = current_user.billing_information
      if @billing_information.present?
        @billing_information.update_attributes(params[:billing_information]) 
      else
        current_user.create_billing_information(params[:billing_information])
      end
      @shipping_information = current_user.shipping_information
      if @shipping_information.present?
        @shipping_information.update_attributes(params[:shipping_information])
      else
        current_user.create_shipping_information(params[:shipping_information])
      end
      flash[:success] = "Information Saved!"  
      render :process
    #rescue => e
      #flash[:error] = "ERROR"
      #render :text => e.messages
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user = nil
    session[:user_id] = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% content_for :head  do %>
<%= javascript_include_tag "jquery-1.10.2", "jquery_ujs" %>
<script type="text/javascript">
$(document).ready(function() {
var score = 0;
var quiz = [
  ['How many moons does Earth have?',1,[0,1,2,3]],
  ['How many moons does Saturn have?',31,[0,14,31,160]],
  ['How many moons does Venus have?',1,[0,1,11,15]]
]; // end quiz 
//get total number of questions
var totalQuestion=quiz.length;

function askQuestion() {
 // pick a  question
 var currentQ=quiz.pop();
 // get the question text
 $('#question').text(currentQ[0]);
 /* call buildAnswers() function to 
    generate radio buttions with multiple choices */
 var answers=buildAnswers(currentQ[2]);
 // add choices to the page
 $('#answers').html(answers);
 $('#answers input').click(function() {
    if ($(this).val()==currentQ[1]) {
      score++;
      $('#result').prepend('That is correct!');
    } else {
      $('#result').prepend('That is incorrect. The correct answer is '+currentQ[1]);
    }
  // show the NEXT button
  $('#next').show();
  }); // end click()
}

function buildAnswers(answers) {
  var answerHTML='';
  // loop through each item in array answers
  for (i=0;i<answers.length;i++) {
    //build radio button
    answerHTML+=' <input name="quiz" type="radio" value="';
    answerHTML+=answers[i] + '">' + answers[i];
  }
  //return completed HTML of radio buttons
  return answerHTML;
}

function giveResults() {
  var results='<p>You got ' + score + ' out of ' + totalQuestion + ' questions correct.</p>';
  $('#questionArea').html(results); 
}

$('#next').click(function() {
  $(this).hide();
  $('#result').text('');
  if (quiz.length==totalQuestion) {
    $(this).val('Next Question >>');
  } else if (quiz.length==1) {
    $(this).val('Show results');
  }
  if (quiz.length>0) {
    askQuestion();
  } else {
    giveResults();
  }
});


}); // end read
</script>
<% end %>

<h1>Debugging with Firebug 
  <%= link_to "Login", login_url if current_user.blank? %> 
  <%= link_to "Sign Up", signup_url if current_user.blank? %> 
  <%= link_to "Sign Out", signout_url, method: "delete" if current_user.present? %>
</h1>
<div id="questionArea">
  <p id="question"></p>
  <p id="answers"></p>
  <p id="result"></p>
  <input type="button" value="Start Quiz" id="next">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Chapter09</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= yield :head %>
</head>
<body id="twoCol">
<div id="container">
<div id="banner"><img src="/assets/banner.png" alt="JavaScript: The Missing Manual" width="760" height="65"><span id="badge"><a href="http://www.sawmac.com/missing/js/"></a></span></div>

<div id="contentWrap">
<div id="main">
  <% flash.each do |key, value| %> 
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %> 
  <%= yield %>
</div>
<div id="sidebar">
<h2>Script 9.2</h2>
</div>
</div>

<div id="footer"><em>&#8220;Building Interactive Web Sites with JavaScript&#8221;</em></div>
</div>
</body>
</html>

app/views/users/new.html.erb
<% content_for :head do %>
<script type="text/javascript">
$(document).ready(function() {
  $('#signup').validate({
   rules: {
     email: {
        required: true,
        email: true
     },
     password: {
        required: true,
        rangelength:[8,16]
     },
     confirm_password: {equalTo:'#password'},
     spam: "required"
   }, //end rules
   messages: {
      email: {
         required: "Please supply an e-mail address.",
         email: "This is not a valid email address."
       },
      password: {
        required: 'Please type a password',
        rangelength: 'Password must be between 8 and 16 characters long.'
      },
      confirm_password: {
        equalTo: 'The two passwords do not match.'
      }
   },
   errorPlacement: function(error, element) { 
       if ( element.is(":radio") || element.is(":checkbox")) {
          error.appendTo( element.parent()); 
        } else {
          error.insertAfter(element);
        } 
    } 

  }); // end validate 
}); // end ready()
</script>
<% end %>

  <h1>Signup Form  </h1>
  <form action="/users" method="post" name="signup" id="signup">
    <div>
      <label for="name" class="label">Name </label>
      <input name="user[name]" type="text" class="required" id="name" title="Please type your name.">
    </div>
    <div>
      <label for="email" class="label">E-mail Address</label>
      <input name="user[email]" type="text" id="email">
    </div>
    <div>
      <label for="password" class="label">Password</label>
      <input name="user[password]" type="password" id="password">
    </div>
    <div>
      <label for="confirm_password" class="label">Confirm Password</label>
      <input name="user[password_confirmation]" type="password" id="confirm_password">
    </div>
<div><span class="label">Hobbies</span>
      <input name="user[heliskiing]" type="checkbox" id="heliskiing" value="heliskiing"  class="required" title="Please check at least 1 hobby.">
      <label for="heliskiing">Heli-skiing</label>
      <input name="user[pickle]" type="checkbox" id="pickle" value="pickle">
      <label for="pickle">Pickle eating</label>
      <input name="user[walnut]" type="checkbox" id="walnut" value="walnut">
      <label for="walnut">Making walnut butter</label>
    </div>
    <div>
      <label for="dob" class="label">Date of birth</label>
      <input name="user[birthday]" type="text" id="dob" class="date" title="Please type your date of birth using this format: 01/19/2000">
    </div>
    <div>
      <label for="planet" class="label">Planet of Birth</label>
      <select name="user[planet]" id="planet" class="required" title="Please choose a planet.">
        <option value="">--Please select one--</option>
        <option value="earth">Earth</option>
        <option value="mars">Mars</option>
        <option value="alpha centauri">Alpha Centauri</option>
        <option value="forget about it">You've never heard of it</option>
      </select>
    </div>
    <div>
      <label for="comments" class="label">Comments</label>
      <textarea name="user[comments]" cols="15" rows="5" id="comments"></textarea>
    </div>
    <div class="labelBlock">Would you like to receive annoying e-mail froM
       US?        </div>
    <div class="indent">
      <input type="radio" name="user[spam]" id="yes" value="yes" class="required" title="Please select an option">
      <label for="yes">Yes</label>
      <input type="radio" name="user[spam]" id="definitely" value="definitely">
      <label for="definitely">Definitely</label>
      <input type="radio" name="user[spam]" id="choice" value="choice">
      <label for="choice">Do I have a choice?</label>
     </div>
<div>
            <input type="submit" name="submit" id="submit" value="Submit">
    </div>
  </form>

app/views/users/process.html.erb
<% content_for :head do %>
<%= javascript_include_tag "jquery-1.10.2", "jquery_ujs" %>
<% end %>
<h1>
  <%= current_user.name %>'s  Space 
  <% if current_user.present? %>
    <%= link_to "Profile information", profile_path %> 
    <%= link_to "Home Page", root_path %>  
  <% end %>
</h1>

<% current_user.attributes.each do |key, val| %>
  <p><span style="display:inline-block; width:120px;"class="key"><%= key %></span>: <span class="value"><%= truncate(val.to_s, length: 30) %></span></p>
<% end %>
<br />
<h1>   billing_information</h1>
<% current_user.billing_information.attributes.each do |key, val| %>
  <p><span style="display:inline-block; width:190px;"class="key"><%= key %></span>: <span class="value"><%= truncate(val.to_s, length: 30) %></span></p>
<% end %>
<h1>shipping_information</h1>
<% current_user.shipping_information.attributes.each do |key, val| %>
  <p><span style="display:inline-block; width:150px;"class="key"><%= key %></span>: <span class="value"><%= truncate(val.to_s, length: 30) %></span></p>
<% end %>
<p><%= link_to "Log out", signout_url, method: "delete" %></p>

app/views/users/profile.html.erb
<h1><%= current_user.name %> Profile Information </h1>
<form action="/order" method="post" name="form1" id="order">
  <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value=<%= form_authenticity_token() %>></div>

    <form action="" method="post" name="form1" id="order">
  <fieldset>
    <legend>Billing Information</legend>
    <%= form_for :billing_information do |f| %>
      <div>
      <label for="name" class="label">name</label>
      <%= f.text_field :name %>
    </div>
    <div>
       <label for="address" class="label">address</label>
      <%= f.text_field :address %>
    </div>
    <div>
     <label for="city" class="label">city</label>
      <%= f.text_field :city %>
    </div>


    <div>
      <label for="state" class="label">State/Province</label>
      <%= f.text_field :state %>
    </div>

    <div>
      <label for="postal_code" class="label">postal code</label>
      <%= f.text_field :postal_code %>
    </div>
       <div>
         <label for="country" class="label" value="">Country</label>
      <%= country_select("billing_information", "country", nil, {iso_codes: true}, {class: 'billing_information'} )%>
      <label for="country" class="label" value>Country</label>
          </div>
          <div>

          <%#<label for="payment_method" class="label">%>
    <div><span class="label">Payment Method</span>
          <%= f.radio_button "payment_method", id="paypal" %>
      <label for="billing_information_payment_method_paypal" >PayPal</label>

          <%= f.radio_button "payment_method", id="visa" %>
          <label for="billing_information_payment_method_visa" >Visa</label>

          <%= f.radio_button "payment_method", id="mastercard" %>
          <label for="billing_information_payment_method_mastercard">MasterCard</label>

        </div>
    <div id="creditCard" class="indent">
 <%#<% if @billing_information.payment_method == "paypal"%>%>
   <%#<% :card_number.hidden %>%>
      <%#<% end%>%>

  <div>
      <label for="card_number" class="label">Card Number</label>
      <%= f.text_field :card_number %>
    </div>
  <div>
      <label for="expiration" class="label">Expiration Date</label>
      <%= f.text_field :expiration_date  %>
    </div>




  </fieldset>
  <fieldset>
    <legend>Shipping Information</legend>
    <div class="indent">
      <%  if @billing_information.same_as_shipping_information.present? %> 
      <input type="checkbox" name="billing_information[same_as_shipping_information]" id="hideShip" checked="same_as_shipping_information">
     <% else %>
      <input type="checkbox" name="billing_information[same_as_shipping_information]" id="hideShip" >
    <% end %>
      <label for="hideShip">Same as billing</label>
    </div>


    <div id="shipping">
      <div> <%#<%= form_tag("shipping_infomation", method: "get") do %>%>
          <%= label_tag('address', "shipping") %>
            <%#<%= text_field_tag :adress, @shipping_information[:address] %>%>
            <%= text_field_tag 'shipping_information[address]',:address %>
            <%= submit_tag("Se") %> </div>
            <%#<% end %>%>
          <div>
        <%#<label for="shipName" class="label">Name</label>%>
        <%#<input value=<%= @shipping_information.name %> ""  name="shipping_information[name]" type="text" id="shipName" size="36">%>
      </div>
      <div>
        <label for="shipAddress" class="label">address</label>
        <input value=<%= @shipping_information.address %> "" name="shipping_information[address]" type="text" id="shipAddress" size="36">
      </div>
      <div>
        <label for="shipCity" class="label">City</label>
        <input value=<%= @shipping_information.city %> "" name="shipping_information[city]" type="text" id="shipCity" size="36">
      </div>
      <div>
        <label for="shipState" class="label">State/Province</label>
        <input value=<%= @shipping_information.state %> ""  name="shipping_information[state]" type="text" id="shipState" size="36">
      </div>
      <div>
        <label for="shipZip" class="label">Postal Code</label>
        <input value=<%= @shipping_information.postal_code %> "" name="shipping_information[postal_code]" type="text" id="shipZip" size="36">
      </div>
      <div>
      <label for="country" class="label" value>Country</label>
      <%= country_select("shipping_information", "country", nil, {iso_codes: true}, {class: 'shipping_information'} )%>
      </div>
    </div>
  </fieldset>

   <%= f.submit :submit %>
    <% end %>


  <%#<input type="submit" name="submit" id="submit" value="Submit">%>
</form>